const dataJadwal = [
    {
        "id_jadwal": "jdwl_20260601",
        "tanggal": "2026-06-01",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260604",
        "tanggal": "2026-06-04",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260606",
        "tanggal": "2026-06-06",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260608",
        "tanggal": "2026-06-08",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260611",
        "tanggal": "2026-06-11",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260613",
        "tanggal": "2026-06-13",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260615",
        "tanggal": "2026-06-15",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260618",
        "tanggal": "2026-06-18",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260620",
        "tanggal": "2026-06-20",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260622",
        "tanggal": "2026-06-22",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260625",
        "tanggal": "2026-06-25",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260627",
        "tanggal": "2026-06-27",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260629",
        "tanggal": "2026-06-29",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260702",
        "tanggal": "2026-07-02",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260704",
        "tanggal": "2026-07-04",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260706",
        "tanggal": "2026-07-06",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260709",
        "tanggal": "2026-07-09",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260711",
        "tanggal": "2026-07-11",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260713",
        "tanggal": "2026-07-13",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260716",
        "tanggal": "2026-07-16",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260718",
        "tanggal": "2026-07-18",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260720",
        "tanggal": "2026-07-20",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260723",
        "tanggal": "2026-07-23",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260725",
        "tanggal": "2026-07-25",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260727",
        "tanggal": "2026-07-27",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260730",
        "tanggal": "2026-07-30",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260801",
        "tanggal": "2026-08-01",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260803",
        "tanggal": "2026-08-03",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260806",
        "tanggal": "2026-08-06",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260808",
        "tanggal": "2026-08-08",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260810",
        "tanggal": "2026-08-10",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260813",
        "tanggal": "2026-08-13",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260815",
        "tanggal": "2026-08-15",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260817",
        "tanggal": "2026-08-17",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260820",
        "tanggal": "2026-08-20",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260822",
        "tanggal": "2026-08-22",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260824",
        "tanggal": "2026-08-24",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260827",
        "tanggal": "2026-08-27",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260829",
        "tanggal": "2026-08-29",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260831",
        "tanggal": "2026-08-31",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260903",
        "tanggal": "2026-09-03",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260905",
        "tanggal": "2026-09-05",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260907",
        "tanggal": "2026-09-07",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260910",
        "tanggal": "2026-09-10",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260912",
        "tanggal": "2026-09-12",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260914",
        "tanggal": "2026-09-14",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260917",
        "tanggal": "2026-09-17",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260919",
        "tanggal": "2026-09-19",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260921",
        "tanggal": "2026-09-21",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260924",
        "tanggal": "2026-09-24",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20260926",
        "tanggal": "2026-09-26",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20260928",
        "tanggal": "2026-09-28",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20261001",
        "tanggal": "2026-10-01",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20261003",
        "tanggal": "2026-10-03",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20261005",
        "tanggal": "2026-10-05",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20261008",
        "tanggal": "2026-10-08",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20261010",
        "tanggal": "2026-10-10",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20261012",
        "tanggal": "2026-10-12",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20261015",
        "tanggal": "2026-10-15",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20261017",
        "tanggal": "2026-10-17",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20261019",
        "tanggal": "2026-10-19",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20261022",
        "tanggal": "2026-10-22",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20261024",
        "tanggal": "2026-10-24",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20261026",
        "tanggal": "2026-10-26",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20261029",
        "tanggal": "2026-10-29",
        "hari": "Kamis",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Pemda Bekasi"
    },
    {
        "id_jadwal": "jdwl_20261031",
        "tanggal": "2026-10-31",
        "hari": "Sabtu",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    },
    {
        "id_jadwal": "jdwl_20261102",
        "tanggal": "2026-11-02",
        "hari": "Senin",
        "sesi": "16.00 - 18.00 (2 Jam)",
        "pemanasan": "Pemanasan, Kalibrasi Pantulan, Mini Soft Tennis.",
        "latihan": "Endurance, Agility Footwork Cepat.",
        "utama": "Latihan Variasi Pukulan Dasar, Forehand, Backhand, Slice, Volley, Drive Volley, Half Volley dan Service, Drill Penempatan Bola.",
        "simulasi": "Bermain Full Set Taktik Intensif, Game.",
        "evaluasi": "Penguatan Fisik, Pendinginan.",
        "tempat": "Lapangan Tenis Wibawa Mukti"
    }
];
